### ISSUE TITLE
Link to existing project

### ISSUE THREAD

**Issue by jcbhmr** [spenserblack/.gitattributes#1]
Hello again! 👋

I saw this repo in my GitHub Feed and remembered that I saw something similar that already existed. I think it would be cool to link to an existing project that covers a similar idea: https://github.com/alexkaratarakis/gitattributes

**Comment by spenserblack** [comment]
Good idea! Yeah, this repo is currently for my personal uses and repeated patterns, so it would be a good idea to point to that project in case someone stumbles on this one.

I'd accept a PR if you want, otherwise I'll get to this later 🙂

**Comment by jcbhmr** [comment]
Would it also be possible to contribute your ideas to the existing list? 🤔

**Comment by spenserblack** [comment]
[Looks like you beat me to the punch](https://github.com/alexkaratarakis/gitattributes/pull/182).

Although that project's `Commmon.gitattributes` does give me the idea to merge some of mine together.
