### ISSUE TITLE
`.yarnrc linguist-language=YAML`?

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/.gitattributes#3]
Wanting to see if `.yarnrc` files could get syntax highlighting in GitHub, I found that:

- [`.yarnrc` uses the same format as v1 `yarn.lock`](https://github.com/yarnpkg/yarn/blob/158d96dce95313d9a00218302631cd263877d164/src/registries/yarn-registry.js#L89) (if I skimmed correctly)
- YAML highlighting is considered "good enough" for v1 `yarn.lock` files: https://github.com/github-linguist/linguist/pull/4761

cc @jcbhmr since you've taken interest in gitattributes projects :slightly_smiling_face:

- Should this be registered to github-linguist, or is `.yarnrc` not YAML-like enough? (`yarn.lock` is position where old files are YAML-like, new files are YAML)

I'm probably not going to go through with this, but I at least wanted to write down my findings *somewhere* before my thoughts disappear in the ether.

**Comment by jcbhmr** [comment]
It would appear from the official docs that you're correct. They are now YAML, they used to be similar to yarn.lock. https://yarnpkg.com/configuration/yarnrc

![image](https://github.com/spenserblack/.gitattributes/assets/61068799/59fa8a93-e039-4508-bfc5-68dc1f8e9e93)

Previously they were NOT yaml and were instead name-value pairs separated by a space (it appears)
https://classic.yarnpkg.com/lang/en/docs/yarnrc/

(disclaimer: i use primarily default npm 😅 so idk 100%) So in summary, I think `yarnrc.yml` files are covered by file extension `*.yml` association but  yarnrc could be special grammar like npmrc https://github.com/search?q=repo%3Agithub-linguist%2Flinguist%20.npmrc&type=code or "close enough" to something else. or just say "too bad yarn 1.0 users git gud with yarnrc.yml 😎"

**Comment by jcbhmr** [comment]
As for the `.yarnrc linguist-language=YAML` i'd just say "tough luck, deal with plain text" since a) there's not too many options/complexity that it's not really worth the hassle and b) use the modern .yarnrc.yml 😎
